apiVersion: apps/v1
kind: Deployment
metadata:
  name: partnerapp-backend-deployment
spec:
  selector:
    matchLabels:
      app: partnerapp-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: partnerapp-backend
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: php-sessions
        persistentVolumeClaim:
          claimName: php-sessions-claim
      containers:
        - name: partnerapp-backend
          image: 689072714931.dkr.ecr.eu-west-1.amazonaws.com/partnerapp-backend-repository:production
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: [ "SYS_PTRACE" ]
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - '-c'
                  - stop.sh
          readinessProbe:
            httpGet:
              path: /health.php
              port: 80
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
          - name: php-sessions
            mountPath: /php-sessions
          env:
          - name: APP_ENV
            value: "production"
          - name: PA_SERVER_NAME
            value: "production.api.pa.job-step.com"
          - name: CRM_URL
            value: "https://production.crm.job-step.com/"
          - name: JS_URL
            value: "https://production.js.job-step.com/"
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: DB_HOST
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: DB_DATABASE
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: partnerapp-backend-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health.php
spec:
  selector:
    app: partnerapp-backend
  ports:
    - port: 80
      targetPort: 80
