 <?php
 
 echo md5(""); exit();
// // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://jobstep-app.com/jobstep-partner/api?action=loginDemo');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, "jp_email=b.bender@job-step.net&jp_password=smax2max");


// $result = curl_exec($ch);
// if (curl_errno($ch)) {
    // echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);
// var_dump ($result);

 ?>

 <?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://jobstep-app.com/jobstep-partner/api?action=candidate_list_demo');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "token=4979cc88e5145e63e5c81c25&lang=ba");


$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
var_dump ($result);
echo json_decode($result, true);

 ?>


 <?php
// // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://jobstep-app.com/jobstep-partner/api?action=register_custom_user');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, "jp_email=b.bender@job-step.net&jp_password=smax2max&jp_fcmtoken=12");


// $result = curl_exec($ch);
// if (curl_errno($ch)) {
    // echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);
// var_dump ($result);

?>