[www]
user = www-data
group = www-data
listen = /run/php/php7.1-fpm.sock
listen.owner = www-data
listen.group = www-data

catch_workers_output = yes
clear_env = no

pm = ondemand
pm.max_children = 50
pm.max_requests = 4096
pm.process_idle_timeout = 1s

php_admin_flag[log_errors] = on
php_flag[display_errors] = off

php_admin_value[memory_limit] = 512M
php_admin_value[max_execution_time] = 180
php_admin_value[max_input_nesting_level] = 128
php_admin_value[max_input_vars] = 6000
php_admin_value[post_max_size] = 36M
php_admin_value[upload_max_filesize] = 32M

slowlog = /dev/stderr
request_slowlog_timeout = 15s
