apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crm-files-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: crm-files-pv
  resources:
    requests:
      storage: 1Gi
