apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-contracts-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: pdf-contracts-pv
  resources:
    requests:
      storage: 5Gi
