apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: js-files-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: js-files-pv
  resources:
    requests:
      storage: 100Gi
