<?php
$json_niz_srb = '

[
  {
    "first_name": "Stefan",
    "last_name": "Stefan",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "auto-električar",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Autoelektricar",
    "date_of_birth": "1/17/90",
    "phone_number": "381638023348"
  },
  {
    "first_name": "Goran",
    "last_name": "Stevanovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "auto-električar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Elektrotehnicar energetike",
    "date_of_birth": "8/3/81",
    "phone_number": "381638939600"
  },
  {
    "first_name": "Milenko",
    "last_name": "Krsmanovic",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "auto-električar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar za volkswagen vozila",
    "date_of_birth": "3/31/97",
    "phone_number": "381616286995"
  },
  {
    "first_name": "Filip",
    "last_name": "Petrovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Elektotehnicaracunara",
    "date_of_birth": "5/26/03",
    "phone_number": "381665507701"
  },
  {
    "first_name": "Ivan",
    "last_name": "Stanojevic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "bravar",
    "date_of_birth": "04/29/1984",
    "phone_number": "381611873887"
  },
  {
    "first_name": "Nikola",
    "last_name": "Đorđević",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "srednja masinska skola:smer-Mehanicar",
    "date_of_birth": "12/05/1994",
    "phone_number": "381677706297"
  },
  {
    "first_name": "Siniša",
    "last_name": "Sušić",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar V- stepen",
    "date_of_birth": "3/14/82",
    "phone_number": "381616469173"
  },
  {
    "first_name": "Nikola",
    "last_name": "Radmanović",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar",
    "date_of_birth": "11/30/01",
    "phone_number": "381616392532"
  },
  {
    "first_name": "Bojan",
    "last_name": "Radosavljević",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar mašinski smer",
    "date_of_birth": "9/20/82",
    "phone_number": "38162223031"
  },
  {
    "first_name": "Bojan",
    "last_name": "Naskovic",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Masinsko tehnika skola smre auto mehanicar",
    "date_of_birth": "5/25/87",
    "phone_number": "381631794601"
  },
  {
    "first_name": "Petar",
    "last_name": "Simić",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehanicar",
    "date_of_birth": "10/27/04",
    "phone_number": "381642362428"
  },
  {
    "first_name": "Darko",
    "last_name": "Gaća",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "automehanicar",
    "date_of_birth": "10/18/1997",
    "phone_number": "381691636036"
  },
  {
    "first_name": "Vlada",
    "last_name": "Bogdanovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "automehanicar za motorna vozila",
    "date_of_birth": "09/01/1992",
    "phone_number": "381611318735"
  },
  {
    "first_name": "Bojan",
    "last_name": "Petkov",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar",
    "date_of_birth": "09/10/1994",
    "phone_number": "381621076275"
  },
  {
    "first_name": "Nikola",
    "last_name": "Kuštrimović",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Mašinski tehničar motornih vozila",
    "date_of_birth": "5/26/94",
    "phone_number": "381653197800"
  },
  {
    "first_name": "Velibor",
    "last_name": "Stanojevic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "automehanicar",
    "date_of_birth": "06/15/1983",
    "phone_number": "381600353930"
  },
  {
    "first_name": "Rade",
    "last_name": "Novakovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Automehaničar",
    "date_of_birth": "5/6/84",
    "phone_number": "381655057666"
  },
  {
    "first_name": "Nenad",
    "last_name": "Zdravkovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "ne",
    "završeno_obrazovanje/smjer:": "automehaničar",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "automehaničar",
    "date_of_birth": "08/15/1982",
    "phone_number": "381631434579"
  },
  {
    "first_name": "Miljan",
    "last_name": "Bukvić",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "automehatroničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Elektrotehnika",
    "date_of_birth": "3/23/92",
    "phone_number": "381649953661"
  },
  {
    "first_name": "Darko",
    "last_name": "Zivkovic",
    "nivo_njemackog": "C2",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "automehatroničar",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Mehanicar",
    "date_of_birth": "9/21/85",
    "phone_number": "38162261684"
  },
  {
    "first_name": "Miroliub",
    "last_name": "Milosavljevic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "osnovna skola sa prvom godinom srednje",
    "date_of_birth": "05/23/1984",
    "phone_number": "381611339280"
  },
  {
    "first_name": "Boris",
    "last_name": "Đorđević",
    "nivo_njemackog": "A2",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Mehanicar laboratorisjke i medicinske opreme u srednjoj Masinskoj skoli",
    "date_of_birth": "7/26/88",
    "phone_number": "381604499595"
  },
  {
    "first_name": "Aleksa",
    "last_name": "Markovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Mašinski Tehničar Motornih Vozila",
    "date_of_birth": "6/27/05",
    "phone_number": "381616667398"
  },
  {
    "first_name": "omer",
    "last_name": "Zli",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_manje_od_1_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Osnovno skola",
    "date_of_birth": "10/30/02",
    "phone_number": "381654229567"
  },
  {
    "first_name": "Jovan",
    "last_name": "Stojanovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_više_od_3_godine",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "tehnicar drumskog saobracaja",
    "date_of_birth": "9/20/00",
    "phone_number": "381637160952"
  },
  {
    "first_name": "Marko",
    "last_name": "Vilovski",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "da_-_više_od_5_godina",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Tehnicka Skola Kikinda Tehnicar za kompijutersko upravljanje",
    "date_of_birth": "7/14/96",
    "phone_number": "381611341144"
  },
  {
    "first_name": "Stefan",
    "last_name": "Šešić",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Zaštita životne sredine, VI - 2 stepen više stručne spreme.",
    "date_of_birth": "3/31/99",
    "phone_number": "381601534003"
  },
  {
    "first_name": "Nikola",
    "last_name": "Nikola",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Tehnicki fakultet, doktor direktne prodaje.",
    "date_of_birth": "12/1/88",
    "phone_number": "381637421596"
  },
  {
    "first_name": "Nemanja",
    "last_name": "Bukurecki",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Средња техничка школа у старој пазови, смер машински техничар за компљутерско конструисање",
    "date_of_birth": "9/22/95",
    "phone_number": "381603300418"
  },
  {
    "first_name": "Nikola",
    "last_name": "Bogdanovic",
    "nivo_njemackog": "A1",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Kuvar",
    "date_of_birth": "5/21/93",
    "phone_number": "436677706971"
  },
  {
    "first_name": "Vladimir",
    "last_name": "Ugrenovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Bravar-monter,monter vetilacije",
    "date_of_birth": "11/23/82",
    "phone_number": "381648478090"
  },
  {
    "first_name": "Lazar",
    "last_name": "Vujinovic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "ne",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Srednja skola",
    "date_of_birth": "3/26/98",
    "phone_number": "381601632785"
  },
  {
    "first_name": "Zoran",
    "last_name": "Radosavljevic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "CE",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "EU-državljanin",
    "smjer_ostalo": "Moler",
    "date_of_birth": "12/8/82",
    "phone_number": "385916061137"
  },
  {
    "first_name": "Dino",
    "last_name": "Salihovic",
    "nivo_njemackog": "A2",
    "vozacka_dozvola": "B",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Masinski Tehnicar za kompijutersko upravljanje (CNC masine)",
    "date_of_birth": "6/30/99",
    "phone_number": "381655587359"
  },
  {
    "first_name": "bolejevtic",
    "last_name": "Jevtic",
    "nivo_njemackog": "Bez znanja",
    "vozacka_dozvola": "C",
    "završeno_obrazovanje/smjer:": "ostalo",
    "radno_iskustvo": "ne",
    "drzavljanstvo": "NON-EU državljanin",
    "smjer_ostalo": "Vozac motornih vozila",
    "date_of_birth": "12/2/01",
    "phone_number": "381612139809"
  }
]


';
// echo $json_niz;

?>

